import { Router, type IRouter } from "express";
import { aiRateLimit } from "../lib/security";
import healthRouter from "./health";
import authRouter from "./auth";
import farmsRouter from "./farms";
import marketRouter from "./market";
import portfolioRouter from "./portfolio";
import farmerRouter from "./farmer";
import kycRouter from "./kyc";
import aiKycRouter from "./ai-kyc";
import loansRouter from "./loans";
import groupsRouter from "./groups";
import adminRouter from "./admin";
import cropPricesRouter from "./crop-prices";
import walletRouter from "./wallet";
import notificationsRouter from "./notifications";
import aiChatRouter from "./ai-chat";
import newsRouter from "./news";
import priceAlertsRouter from "./price-alerts";
import aiRouter from "./ai";
import portfolioManagerRouter from "./portfolio-manager";
import reinvestmentRouter from "./reinvestment";
import investorFeedRouter from "./investor-feed";
import ordersRouter from "./orders";
import watchlistRouter from "./watchlist";
import stellarRouter from "./stellar";
import uploadRouter from "./upload";
import agribusinessRouter from "./agribusiness";
import rainfallRouter from "./rainfall";
import portfolioRoiRouter from "./portfolio-roi";
import totpRouter from "./totp";
import transactionsRouter from "./transactions";
import farmerHealthRouter from "./farmer-health";
import harvestRouter from "./harvest";
import reviewsRouter from "./reviews";
import supportRouter from "./support";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(farmsRouter);
router.use(marketRouter);
router.use(portfolioRouter);
router.use(farmerRouter);
router.use(kycRouter);
router.use(aiKycRouter);
router.use(loansRouter);
router.use(groupsRouter);
router.use(adminRouter);
router.use(cropPricesRouter);
router.use(walletRouter);
router.use(notificationsRouter);
router.use(aiRateLimit, aiChatRouter);
router.use(newsRouter);
router.use(priceAlertsRouter);
router.use(aiRateLimit, aiRouter);
router.use(portfolioManagerRouter);
router.use(reinvestmentRouter);
router.use(investorFeedRouter);
router.use(ordersRouter);
router.use(watchlistRouter);
router.use(stellarRouter);
router.use(uploadRouter);
router.use(agribusinessRouter);
router.use(rainfallRouter);
router.use(portfolioRoiRouter);
router.use(totpRouter);
router.use(transactionsRouter);
router.use(aiRateLimit, farmerHealthRouter);
router.use(harvestRouter);
router.use(reviewsRouter);
router.use(supportRouter);

export default router;
