// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/video1.tsx": () => import("../components/mockups/video1.tsx"),
  "./components/mockups/video2.tsx": () => import("../components/mockups/video2.tsx"),
  "./components/mockups/video3.tsx": () => import("../components/mockups/video3.tsx"),
  "./components/mockups/video4.tsx": () => import("../components/mockups/video4.tsx"),
  "./components/mockups/video5.tsx": () => import("../components/mockups/video5.tsx"),
  "./components/mockups/video6.tsx": () => import("../components/mockups/video6.tsx")
};
